# Generated by Django 3.1.7 on 2021-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210314_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Артикул товара'),
        ),
    ]
