# Generated by Django 3.1.7 on 2021-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210511_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='', verbose_name='Документация'),
            preserve_default=False,
        ),
    ]
